### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by bamtan** [notcammy/PyTikTokScraper#6]
hi cammy i'm getting this error :rage1: 

```bash
$ python3 -m pytiktokscraper --l 11504906 -uid
---------------------------------------------------------------------------
[I] PYTIKTOKSCRAPER (SCRIPT V1.9 - PYTHON V3.6.6) - 11-25-2019 05:46:50 PM
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/live/.pyenv/versions/3.6.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/live/.pyenv/versions/3.6.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/shares/livetmp/tiktok/pytiktokscraper/__main__.py", line 12, in <module>
    startup.run()
  File "/mnt/shares/livetmp/tiktok/pytiktokscraper/startup.py", line 160, in run
    response_user = api.get_user_info(ptts.tt_target_id)
  File "/mnt/shares/livetmp/tiktok/pytiktokscraper/api.py", line 80, in get_user_info
    return request_response.json() if request_response else None
  File "/home/live/.pyenv/versions/3.6.6/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/live/.pyenv/versions/3.6.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/live/.pyenv/versions/3.6.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/live/.pyenv/versions/3.6.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by reliefs** [comment]
same

**Comment by notcammy** [comment]
@reliefs Sorry, this project is no longer being maintained as Tiktok's API is not publicly available and constantly changing, this combined with a loss of interest. 

I recommend using a different project but feel free to pick up development yourself if you wish to do so.
